// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(registerHelper) {
    registerHelper('helper_striptags', function(html) {
      var comments, tags;
      tags = /<\/?([a-z][a-z0-9]*)\b[^>]*>/gi;
      comments = /<!--[\s\S]*?-->|<\?(?:php)?[\s\S]*?\?>/gi;
      return html.replace(comments, '').replace(tags, '');
    });
    registerHelper('helper_htmlescape', function(html) {
      return html.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#039;').replace(/>/g, '&gt;').replace(/</g, '&lt;');
    });
    registerHelper('helper_urlencode', function(text) {
      return encodeURIComponent(text);
    });
    return registerHelper('helper_money', function(number) {
      var dec, n, prec, s, sep, toFixedFix;
      if (number === false) {
        return '';
      }
      number = (number + '').replace(/[^0-9+\-Ee.]/g, '');
      n = !isFinite(+number) ? 0 : +number;
      prec = 0;
      sep = ' ';
      dec = '.';
      s = '';
      toFixedFix = function(n, prec) {
        var k;
        k = Math.pow(10, prec);
        return '' + (Math.round(n * k)) / k;
      };
      s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
      if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
      }
      if ((s[1] || '').length < prec) {
        s[1] = s[1] || '';
        s[1] += new Array(prec - s[1].length + 1).join('0');
      }
      return s.join(dec);
    });
  };

}).call(this);
