// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(registerHelper) {
    return registerHelper('helper_length', function(hash) {
      if (typeof hash.length === 'undefined') {
        return Object.keys(hash).length;
      } else {
        return hash.length;
      }
    });
  };

}).call(this);
