// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(registerHelper) {
    return registerHelper('helper_wrap', function(text, options) {
      var length, next, short, word, words, _i, _len;
      if (options == null) {
        options = {};
      }
      options = options.hash != null ? options.hash : options;
      length = parseInt(options.size || 0, 10);
      if (length <= 0) {
        length = 40;
      }
      if (text.length > length) {
        length = length - 1;
        short = '';
        words = text.split(' ');
        for (_i = 0, _len = words.length; _i < _len; _i++) {
          word = words[_i];
          if (word !== '' && word !== ' ') {
            next = short + word;
            if (next.length >= length) {
              break;
            }
            short += word + ' ';
          }
        }
        short = short.slice(0, -1);
        if (text !== short) {
          text = short + '…';
        }
      }
      return text;
    });
  };

}).call(this);
