// Generated by CoffeeScript 1.4.0
(function() {
  var path;

  path = require('path').normalize(__dirname);

  exports.helpers = function(app, engine) {
    var fn, name, _i, _len, _ref, _results;
    _ref = ['datetime', 'format', 'length', 'wrap'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      fn = require("" + path + "/helpers/" + name);
      _results.push(fn.call(app, engine.registerHelper));
    }
    return _results;
  };

}).call(this);
